### ISSUE TITLE
Read images & pairing data from a csv

### ISSUE THREAD

**Issue by bangxiangyong** [Dr-Eti/ShwypeHammer_shinyswipr_revisited#2]

**Comment by Dr-Eti** [comment]
Hi Xiang, feel free to assign this to me - currently looking into it.
If I don't manage by this week I will ask for your help...

**Comment by bangxiangyong** [comment]
- Commit 8b24c40d51a90bf40bdd49ce5a06e38a3cea4452 has a wip script for pairing unique rows to form the edge list
- Awaiting read from csv to fully test out the pairing script

**Comment by Dr-Eti** [comment]
This is done but need to figure out how to commit...

**Comment by bangxiangyong** [comment]
Let's wait and review the commit that resolves this issue before closing 👍

**Comment by Dr-Eti** [comment]
this has been fixed with same commit as another issue 1a1cb87
