### ISSUE TITLE
Save swipe data into Google sheet

### ISSUE THREAD

**Issue by bangxiangyong** [Dr-Eti/ShwypeHammer_shinyswipr_revisited#4]
- GG sheet seems not to be very stable so need to stablilise it 
- alternatively save into a csv

**Comment by bangxiangyong** [comment]
- Awaiting the pairing of rows from #2 
- Need to know the final required format of the saved sheet 
- Should directly impact #5

**Comment by Dr-Eti** [comment]
Bullet one done - your latest code 8b24c40 looks cool many thanks for that! I may still want to check if expand.grid does a better job ...but let's say it's done!

**Comment by Dr-Eti** [comment]
I have re-enabled your google sheet see commit 32c4404 But I have been experiencing some issues with the Google API. I still believe we need a way to overcome issues with Token generation and accessibility of the spreadsheet

**Comment by bangxiangyong** [comment]
Yes, otherwise for stability issues, we may stick to csv instead for now

**Comment by bangxiangyong** [comment]
Implemented both csv and googlesheet saving capabilities with token handling
4c5262a6a9cf0610e581e06b16fc38cae8054617
