### ISSUE TITLE
Need a way to finish swiping all

### ISSUE THREAD

**Issue by bangxiangyong** [Dr-Eti/ShwypeHammer_shinyswipr_revisited#6]
- need a counter for total cards available

**Comment by bangxiangyong** [comment]
- awaiting the pairings generated from task #2

**Comment by Dr-Eti** [comment]
Commit 1a1cb87 fixes the issue of "pairings" mentioned in the task; It also generates the counter for total cards available; 
However, we still need to handle the "finish" event as it affects the UI - at the moment, the app keeps "listening" for swipes although it records "NAs"; that's not ideal but better than nothing... we need to dynamically operate on the UI when the counter reaches completion

**Comment by Dr-Eti** [comment]
to handle the "end of the card deck" - I guess we should take a look at the so called Dynamic UI in Shiny. There is an excellent book that I have in print but also available online. Chapter 19 is about dynamic UI https://mastering-shiny.org/scaling-modules.html#dynamic-ui

**Comment by Dr-Eti** [comment]
In commit 317d5ba I have made some progresses using a reactive counter that prevents the swipe log from progressing (no more edges are added) upon reaching the maximum number of cards (edges). It's not the final answer but the input to be handed off to the backend app won't be affected by further swipes after the maximum number of cards is reached. the UI however needs work

**Comment by bangxiangyong** [comment]
I have picked up from your work in 543987a3f72aac3560c20476026d009902027807 
I have added a code section for handling the UI update for the final swipe
at the moment it removes the card deck after the final swipe (max cards).
